import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Design system MarketSync ──
        primary: '#091426',
        'primary-container': '#1e293b',
        'primary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#bcc7de',
        'on-primary': '#ffffff',
        'on-primary-container': '#8590a6',
        'on-primary-fixed': '#111c2d',
        'on-primary-fixed-variant': '#3c475a',
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#201100',
        'tertiary-container': '#3c2300',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c88000',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#545f73',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45474c',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bcc7de',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        // ── Extras funcionais ──
        success: '#10b981',
        'success-container': '#dcfce7',
        warning: '#f59e0b',
        'warning-container': '#fef3c7',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Inter', 'monospace'],
      },
      fontSize: {
        'display-price': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'pos-gutter': '12px',
        'container-margin': '24px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(30,41,59,0.06), 0 1px 2px rgba(30,41,59,0.04)',
        modal: '0 4px 12px rgba(30,41,59,0.08)',
      },
    },
  },
  plugins: [],
} satisfies Config;
